#!/usr/bin/env sh

set -o posix

typeset TODODIR="$HOME/.todo"

#
# be helpful
#
help() {
  echo
  echo "Todone!\nA basic todo list.\n"
  echo "Options:"
  echo "  -a  --add       Add a todo"
  echo "  -d  --delete    Delete a todo"
  echo "  -o  --open      Open a todo"
  echo "  -l  --list      List all todos"
  echo "  -c  --clear     Clear all todos"
  echo "  -h  --help      Show this help message"
}

#
# abort with <msg>
#
abort() {
  echo "\n\033[31m✖\033[0m $@" 1>&2
  exit 1
}

#
# success with <msg>
#
success() {
  echo "\n\033[32m✔︎\033[0m $@"
}

#
# todo not found
#
abort_notfound() {
  abort "'$NAME' isn't a todo"
}

#
# todo name not entered
#
abort_noname() {
  abort "Enter a todo name"
}

#
# Make sure the todo folder exists
#
check_create_tododir() {
  command mkdir -p $TODODIR
}

#
# add a todo
#
add() {
  check_create_tododir

  local NAME="$@"
  local FILEPATH="$TODODIR/$NAME.md"

  if [ ! "$NAME" ]; then
    abort_noname
  fi

  if [ ! -f "$FILEPATH" ]; then
    touch "$FILEPATH"
    echo "# $NAME" >> "$FILEPATH"
    success "'$NAME' todo added"
  else
    abort "'$NAME' is already a todo"
  fi
}

#
# delete a todo
#
delete() {
  local NAME="$@"
  local FILEPATH="$TODODIR/$NAME.md"

  if [ ! "$NAME" ]; then
    abort_noname
  fi

  if [ -f "$FILEPATH" ]; then
    rm "$FILEPATH"
    success "'$NAME' todo deleted"
  else
    abort_notfound
  fi
}

#
# open a todo
#
open() {
  local NAME="$@"
  local FILEPATH="$TODODIR/$NAME.md"

  if [ ! "$NAME" ]; then
    abort "Enter a todo to open"
  fi

  if [ $EDITOR ]; then
    local opener=$EDITOR
  else
    local opener="open"
  fi

  if [ -f "$FILEPATH" ]; then
    command $opener "$FILEPATH"
  else
    abort_notfound
  fi
}

#
# clear all todos
#
clear() {
  read -r -p "Are you sure? [y/N] " response
  case $response in
    [yY][eE][sS]|[yY])
      rm $TODODIR/* &> /dev/null
      success "Cleared todos"
      ;;
  esac
}

#
# lists todos
#
list() {
  if [ ! "`ls -tr $TODODIR`" ]; then
    success "Todone!"
    exit
  fi

  echo
  command ls -tr $TODODIR | while read TODO;
  do
    echo "· $TODO" | awk '{sub(/.md/, ""); print $0}'
  done
}

# parse argv
while test $# -ne 0; do
  arg=$1; shift
  case $arg in
    -a|--add) add $@; exit ;;
    -d|--delete) delete $@; exit ;;
    -o|--open) open $@; exit ;;
    -c|--clear) clear; exit ;;
    -d|--list) list; exit;;
    -h|--help) help; exit ;;
    *)
      test $# -eq 1 || abort "Unknown option"
  esac
done

# list todos if no args
list
